In [88]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import make_regression

## Creating a Regression Dataset

In [99]:
X, y = make_regression(n_samples=1000, n_features=3)
y = y.reshape(-1, 1)


X.shape, y.shape

((1000, 3), (1000, 1))

## Adding a 1s Column for the Bias Term

In [100]:
ones_column = np.ones((X.shape[0], 1))
X_augmented = np.hstack((ones_column, X))
X_augmented.shape

(1000, 4)

## Splitting the Data

In [101]:
X_train, X_test, y_train, y_test = train_test_split(
    X_augmented, y, test_size=0.3, random_state=42
)


X_train.shape, X_test.shape, y_train.shape, y_test.shape

((700, 4), (300, 4), (700, 1), (300, 1))

## Initializing the Weights Vector

In [103]:
weights = np.random.randn(X_augmented.shape[1], 1)
weights

array([[ 0.61273649],
       [ 0.18933135],
       [-2.24208829],
       [ 0.31617437]])

## Implementing the Loss Function

In [104]:
def get_loss(y, y_pred):
    return (1 / 2) * np.mean((y - y_pred) ** 2)

## Implementing Gradient Descent Function

In [107]:
def gradient_descent(X, y, W, learning_rate=0.1, iterations=100):
    m = X.shape[0]
    weight = W.copy()

    for i in range(iterations):
        y_pred = X @ weight

        error = y - y_pred

        gradient = -(1 / m) * (X.T @ error)

        weight -= learning_rate * gradient

        loss = get_loss(y, y_pred)

        if (i + 1) % 10 == 0:
            print(f"Iteration {i+1} : loss = {loss:.4f}")

    return weight

## Acquiring the New Weights

In [108]:
new_weights = gradient_descent(X_train, y_train, weights)

Iteration 10 : loss = 588.4392
Iteration 20 : loss = 80.2253
Iteration 30 : loss = 11.3031
Iteration 40 : loss = 1.6330
Iteration 50 : loss = 0.2403
Iteration 60 : loss = 0.0358
Iteration 70 : loss = 0.0054
Iteration 80 : loss = 0.0008
Iteration 90 : loss = 0.0001
Iteration 100 : loss = 0.0000


In [109]:
print("old weights:\n", weights)
print("new weights:\n", new_weights)

old weights:
 [[ 0.61273649]
 [ 0.18933135]
 [-2.24208829]
 [ 0.31617437]]
new weights:
 [[-1.89750467e-03]
 [ 4.66191058e+01]
 [ 4.56950444e+01]
 [ 5.62735671e+01]]


## Testing the New Weights

In [ ]:
y_pred = X_test @ new_weights

get_loss(y_test, y_pred)

1.928992842586472e-05

In [ ]:
from sklearn.metrics import mean_squared_error

mean_squared_error(y_test, y_pred)

3.857985685172944e-05